#!/bin/bash

#SBATCH -J anlyzBD
#SBATCH -n 1 -N 1
#SBATCH -t 1:00:00
#SBATCH -o %A-anlyz.out
#SBATCH -e %A-anlyz.err

# source into the virtual environment
module load miniconda3/24.11.1
module load OpenMPI/4.1.6
module load cuda/12.1.1
module load OpenBLAS/0.3.29
source # path to software, for example: /projects/props/Rob/software/hoomd4.2.1-mod/hoomdmod4.2.1-venv/bin/activate 

# run the analysis file
python sim-analysis-BD.py
