#!/bin/bash
#SBATCH -J updtr
#SBATCH -n 1 -N 1
#SBATCH -t 1:00:00
#SBATCH -o %A-updt.out
#SBATCH -e %A-updt.err

# move out of the hoomd4.2.1-mod/scripts/install-update directory
cd ../../../

# source into the virtual environment
module load miniconda3/24.11.1
module load cmake/3.30.2
module load OpenMPI/4.1.6
module load cuda/12.1.1
module load OpenBLAS/0.3.29
python3 -m venv hoomdmod4.2.1-venv
source hoomdmod4.2.1-venv/bin/activate

#recompile and reinstall hoomd-blue
cmake --build build/hoomd
cmake --install build/hoomd
